root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd/main.go"
bin = "tmp/main.exe"
full_bin = "./tmp/main.exe"
include_ext = ["go", "tpl", "tmpl", "html", ".env"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
delay = 1000
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_file = []
kill_delay = "0s"
log = "air_errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = true

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true